### ISSUE TITLE
Error 24007

### ISSUE THREAD

**Issue by mikedizon** [ptagr/fbm-bot#1]
Getting Error 24007 when I try to authorize payment. Have you seen this?

**Comment by ptagr** [comment]
@mikedizon : you need your app/page to be whitelisted for payments. Also you need the pgp key to be set up for that. (Usually the later that will give you the 24007 error)

**Comment by mikedizon** [comment]
I am whitelisted, and I sent my gpg public key with the curl command listed in the example.

**Comment by ptagr** [comment]
is it still not working?

**Comment by mikedizon** [comment]
It's fixed, thanks for following up.
